name: autello

services:
  backend:
    image: registry.otiva.ru/autello-backend:latest
    container_name: autello-backend
    restart: unless-stopped
    pull_policy: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - shared-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    image: registry.otiva.ru/autello-web:latest
    container_name: autello-web
    restart: unless-stopped
    pull_policy: always
    networks:
      - shared-network
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  shared-network:
    name: shared-network
    external: true
